version: '3'
services: 
  api: 
    container_name: api
    env_file:
      - ./api/.env
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api/app:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db: 
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mailcheck
      TZ: "Asia/Tokyo"
    volumes: 
      - ./db/data:/var/lib/postgresql
      - ./db/sql:/docker-entrypoint-initdb.d
    
  adm:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=docker
    depends_on:
      - db
